// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

public interface ACKOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ACK)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool OK = 1;</code>
   * @return The oK.
   */
  boolean getOK();

  /**
   * <code>int32 nextNodeID = 2;</code>
   * @return The nextNodeID.
   */
  int getNextNodeID();
}
