// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

public final class Anello {
  private Anello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JoinData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JoinData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaveData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaveData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ElectionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ElectionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenData_StatsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenData_StatsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Statistics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Statistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HouseData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HouseData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ACK_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ACK_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014anello.proto\"8\n\010JoinData\022\016\n\006sender\030\001 \001" +
      "(\005\022\034\n\010newcomer\030\002 \001(\0132\n.HouseData\"C\n\tLeav" +
      "eData\022\016\n\006sender\030\001 \001(\005\022\014\n\004next\030\002 \001(\005\022\030\n\020e" +
      "mergencyAddress\030\003 \001(\t\"8\n\nUpdateData\022\016\n\006s" +
      "ender\030\001 \001(\005\022\032\n\006houses\030\002 \003(\0132\n.HouseData\"" +
      "B\n\014ElectionData\022\016\n\006sender\030\001 \001(\005\022\021\n\tsenio" +
      "rity\030\002 \001(\005\022\017\n\007elected\030\003 \001(\010\"l\n\tTokenData" +
      "\022$\n\005stats\030\001 \003(\0132\025.TokenData.StatsEntry\0329" +
      "\n\nStatsEntry\022\013\n\003key\030\001 \001(\005\022\032\n\005value\030\002 \001(\013" +
      "2\013.Statistics:\0028\001\".\n\nStatistics\022\r\n\005value" +
      "\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001(\003\"6\n\tHouseData\022\n" +
      "\n\002id\030\001 \001(\005\022\017\n\007address\030\002 \001(\t\022\014\n\004port\030\003 \001(" +
      "\005\"%\n\003ACK\022\n\n\002OK\030\001 \001(\010\022\022\n\nnextNodeID\030\002 \001(\005" +
      "2\236\001\n\013RingNetwork\022\027\n\004Join\022\t.JoinData\032\004.AC" +
      "K\022\031\n\005Leave\022\n.LeaveData\032\004.ACK\022\033\n\006Update\022\013" +
      ".UpdateData\032\004.ACK\022\037\n\010Election\022\r.Election" +
      "Data\032\004.ACK\022\035\n\tPassToken\022\n.TokenData\032\004.AC" +
      "KB\025\n\021sdp.progetto.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JoinData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JoinData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JoinData_descriptor,
        new java.lang.String[] { "Sender", "Newcomer", });
    internal_static_LeaveData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LeaveData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaveData_descriptor,
        new java.lang.String[] { "Sender", "Next", "EmergencyAddress", });
    internal_static_UpdateData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateData_descriptor,
        new java.lang.String[] { "Sender", "Houses", });
    internal_static_ElectionData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ElectionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ElectionData_descriptor,
        new java.lang.String[] { "Sender", "Seniority", "Elected", });
    internal_static_TokenData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TokenData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenData_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_TokenData_StatsEntry_descriptor =
      internal_static_TokenData_descriptor.getNestedTypes().get(0);
    internal_static_TokenData_StatsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenData_StatsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Statistics_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Statistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Statistics_descriptor,
        new java.lang.String[] { "Value", "Timestamp", });
    internal_static_HouseData_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_HouseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HouseData_descriptor,
        new java.lang.String[] { "Id", "Address", "Port", });
    internal_static_ACK_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ACK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ACK_descriptor,
        new java.lang.String[] { "OK", "NextNodeID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
