// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

/**
 * Protobuf type {@code ElectionData}
 */
public final class ElectionData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ElectionData)
    ElectionDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ElectionData.newBuilder() to construct.
  private ElectionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ElectionData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ElectionData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ElectionData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sender_ = input.readInt32();
            break;
          }
          case 16: {

            seniority_ = input.readInt32();
            break;
          }
          case 24: {

            elected_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdp.progetto.grpc.Anello.internal_static_ElectionData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdp.progetto.grpc.Anello.internal_static_ElectionData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdp.progetto.grpc.ElectionData.class, sdp.progetto.grpc.ElectionData.Builder.class);
  }

  public static final int SENDER_FIELD_NUMBER = 1;
  private int sender_;
  /**
   * <code>int32 sender = 1;</code>
   * @return The sender.
   */
  @java.lang.Override
  public int getSender() {
    return sender_;
  }

  public static final int SENIORITY_FIELD_NUMBER = 2;
  private int seniority_;
  /**
   * <code>int32 seniority = 2;</code>
   * @return The seniority.
   */
  @java.lang.Override
  public int getSeniority() {
    return seniority_;
  }

  public static final int ELECTED_FIELD_NUMBER = 3;
  private boolean elected_;
  /**
   * <code>bool elected = 3;</code>
   * @return The elected.
   */
  @java.lang.Override
  public boolean getElected() {
    return elected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sender_ != 0) {
      output.writeInt32(1, sender_);
    }
    if (seniority_ != 0) {
      output.writeInt32(2, seniority_);
    }
    if (elected_ != false) {
      output.writeBool(3, elected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sender_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sender_);
    }
    if (seniority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, seniority_);
    }
    if (elected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, elected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdp.progetto.grpc.ElectionData)) {
      return super.equals(obj);
    }
    sdp.progetto.grpc.ElectionData other = (sdp.progetto.grpc.ElectionData) obj;

    if (getSender()
        != other.getSender()) return false;
    if (getSeniority()
        != other.getSeniority()) return false;
    if (getElected()
        != other.getElected()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender();
    hash = (37 * hash) + SENIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getSeniority();
    hash = (37 * hash) + ELECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getElected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdp.progetto.grpc.ElectionData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.ElectionData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.ElectionData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.ElectionData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdp.progetto.grpc.ElectionData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ElectionData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ElectionData)
      sdp.progetto.grpc.ElectionDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdp.progetto.grpc.Anello.internal_static_ElectionData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdp.progetto.grpc.Anello.internal_static_ElectionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdp.progetto.grpc.ElectionData.class, sdp.progetto.grpc.ElectionData.Builder.class);
    }

    // Construct using sdp.progetto.grpc.ElectionData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sender_ = 0;

      seniority_ = 0;

      elected_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdp.progetto.grpc.Anello.internal_static_ElectionData_descriptor;
    }

    @java.lang.Override
    public sdp.progetto.grpc.ElectionData getDefaultInstanceForType() {
      return sdp.progetto.grpc.ElectionData.getDefaultInstance();
    }

    @java.lang.Override
    public sdp.progetto.grpc.ElectionData build() {
      sdp.progetto.grpc.ElectionData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdp.progetto.grpc.ElectionData buildPartial() {
      sdp.progetto.grpc.ElectionData result = new sdp.progetto.grpc.ElectionData(this);
      result.sender_ = sender_;
      result.seniority_ = seniority_;
      result.elected_ = elected_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdp.progetto.grpc.ElectionData) {
        return mergeFrom((sdp.progetto.grpc.ElectionData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdp.progetto.grpc.ElectionData other) {
      if (other == sdp.progetto.grpc.ElectionData.getDefaultInstance()) return this;
      if (other.getSender() != 0) {
        setSender(other.getSender());
      }
      if (other.getSeniority() != 0) {
        setSeniority(other.getSeniority());
      }
      if (other.getElected() != false) {
        setElected(other.getElected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sdp.progetto.grpc.ElectionData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sdp.progetto.grpc.ElectionData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int sender_ ;
    /**
     * <code>int32 sender = 1;</code>
     * @return The sender.
     */
    @java.lang.Override
    public int getSender() {
      return sender_;
    }
    /**
     * <code>int32 sender = 1;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(int value) {
      
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sender = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = 0;
      onChanged();
      return this;
    }

    private int seniority_ ;
    /**
     * <code>int32 seniority = 2;</code>
     * @return The seniority.
     */
    @java.lang.Override
    public int getSeniority() {
      return seniority_;
    }
    /**
     * <code>int32 seniority = 2;</code>
     * @param value The seniority to set.
     * @return This builder for chaining.
     */
    public Builder setSeniority(int value) {
      
      seniority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 seniority = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeniority() {
      
      seniority_ = 0;
      onChanged();
      return this;
    }

    private boolean elected_ ;
    /**
     * <code>bool elected = 3;</code>
     * @return The elected.
     */
    @java.lang.Override
    public boolean getElected() {
      return elected_;
    }
    /**
     * <code>bool elected = 3;</code>
     * @param value The elected to set.
     * @return This builder for chaining.
     */
    public Builder setElected(boolean value) {
      
      elected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool elected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearElected() {
      
      elected_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ElectionData)
  }

  // @@protoc_insertion_point(class_scope:ElectionData)
  private static final sdp.progetto.grpc.ElectionData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdp.progetto.grpc.ElectionData();
  }

  public static sdp.progetto.grpc.ElectionData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ElectionData>
      PARSER = new com.google.protobuf.AbstractParser<ElectionData>() {
    @java.lang.Override
    public ElectionData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ElectionData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ElectionData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ElectionData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdp.progetto.grpc.ElectionData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

