// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

public interface ElectionDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ElectionData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sender = 1;</code>
   * @return The sender.
   */
  int getSender();

  /**
   * <code>int32 seniority = 2;</code>
   * @return The seniority.
   */
  int getSeniority();

  /**
   * <code>bool elected = 3;</code>
   * @return The elected.
   */
  boolean getElected();
}
