// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

public interface LeaveDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LeaveData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sender = 1;</code>
   * @return The sender.
   */
  int getSender();

  /**
   * <code>int32 next = 2;</code>
   * @return The next.
   */
  int getNext();

  /**
   * <code>string emergencyAddress = 3;</code>
   * @return The emergencyAddress.
   */
  java.lang.String getEmergencyAddress();
  /**
   * <code>string emergencyAddress = 3;</code>
   * @return The bytes for emergencyAddress.
   */
  com.google.protobuf.ByteString
      getEmergencyAddressBytes();
}
