// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

public interface StatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Statistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
