// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

/**
 * Protobuf type {@code TokenData}
 */
public final class TokenData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TokenData)
    TokenDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenData.newBuilder() to construct.
  private TokenData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TokenData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TokenData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              stats_ = com.google.protobuf.MapField.newMapField(
                  StatsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, sdp.progetto.grpc.Statistics>
            stats__ = input.readMessage(
                StatsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            stats_.getMutableMap().put(
                stats__.getKey(), stats__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdp.progetto.grpc.Anello.internal_static_TokenData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetStats();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdp.progetto.grpc.Anello.internal_static_TokenData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdp.progetto.grpc.TokenData.class, sdp.progetto.grpc.TokenData.Builder.class);
  }

  public static final int STATS_FIELD_NUMBER = 1;
  private static final class StatsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, sdp.progetto.grpc.Statistics> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, sdp.progetto.grpc.Statistics>newDefaultInstance(
                sdp.progetto.grpc.Anello.internal_static_TokenData_StatsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                sdp.progetto.grpc.Statistics.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, sdp.progetto.grpc.Statistics> stats_;
  private com.google.protobuf.MapField<java.lang.Integer, sdp.progetto.grpc.Statistics>
  internalGetStats() {
    if (stats_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StatsDefaultEntryHolder.defaultEntry);
    }
    return stats_;
  }

  public int getStatsCount() {
    return internalGetStats().getMap().size();
  }
  /**
   * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
   */

  @java.lang.Override
  public boolean containsStats(
      int key) {
    
    return internalGetStats().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStatsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> getStats() {
    return getStatsMap();
  }
  /**
   * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> getStatsMap() {
    return internalGetStats().getMap();
  }
  /**
   * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
   */
  @java.lang.Override

  public sdp.progetto.grpc.Statistics getStatsOrDefault(
      int key,
      sdp.progetto.grpc.Statistics defaultValue) {
    
    java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> map =
        internalGetStats().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
   */
  @java.lang.Override

  public sdp.progetto.grpc.Statistics getStatsOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> map =
        internalGetStats().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetStats(),
        StatsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, sdp.progetto.grpc.Statistics> entry
         : internalGetStats().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, sdp.progetto.grpc.Statistics>
      stats__ = StatsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stats__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdp.progetto.grpc.TokenData)) {
      return super.equals(obj);
    }
    sdp.progetto.grpc.TokenData other = (sdp.progetto.grpc.TokenData) obj;

    if (!internalGetStats().equals(
        other.internalGetStats())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetStats().getMap().isEmpty()) {
      hash = (37 * hash) + STATS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStats().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdp.progetto.grpc.TokenData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.TokenData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.TokenData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.TokenData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdp.progetto.grpc.TokenData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TokenData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TokenData)
      sdp.progetto.grpc.TokenDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdp.progetto.grpc.Anello.internal_static_TokenData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetStats();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableStats();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdp.progetto.grpc.Anello.internal_static_TokenData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdp.progetto.grpc.TokenData.class, sdp.progetto.grpc.TokenData.Builder.class);
    }

    // Construct using sdp.progetto.grpc.TokenData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableStats().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdp.progetto.grpc.Anello.internal_static_TokenData_descriptor;
    }

    @java.lang.Override
    public sdp.progetto.grpc.TokenData getDefaultInstanceForType() {
      return sdp.progetto.grpc.TokenData.getDefaultInstance();
    }

    @java.lang.Override
    public sdp.progetto.grpc.TokenData build() {
      sdp.progetto.grpc.TokenData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdp.progetto.grpc.TokenData buildPartial() {
      sdp.progetto.grpc.TokenData result = new sdp.progetto.grpc.TokenData(this);
      int from_bitField0_ = bitField0_;
      result.stats_ = internalGetStats();
      result.stats_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdp.progetto.grpc.TokenData) {
        return mergeFrom((sdp.progetto.grpc.TokenData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdp.progetto.grpc.TokenData other) {
      if (other == sdp.progetto.grpc.TokenData.getDefaultInstance()) return this;
      internalGetMutableStats().mergeFrom(
          other.internalGetStats());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sdp.progetto.grpc.TokenData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sdp.progetto.grpc.TokenData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, sdp.progetto.grpc.Statistics> stats_;
    private com.google.protobuf.MapField<java.lang.Integer, sdp.progetto.grpc.Statistics>
    internalGetStats() {
      if (stats_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatsDefaultEntryHolder.defaultEntry);
      }
      return stats_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, sdp.progetto.grpc.Statistics>
    internalGetMutableStats() {
      onChanged();;
      if (stats_ == null) {
        stats_ = com.google.protobuf.MapField.newMapField(
            StatsDefaultEntryHolder.defaultEntry);
      }
      if (!stats_.isMutable()) {
        stats_ = stats_.copy();
      }
      return stats_;
    }

    public int getStatsCount() {
      return internalGetStats().getMap().size();
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */

    @java.lang.Override
    public boolean containsStats(
        int key) {
      
      return internalGetStats().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> getStats() {
      return getStatsMap();
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> getStatsMap() {
      return internalGetStats().getMap();
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */
    @java.lang.Override

    public sdp.progetto.grpc.Statistics getStatsOrDefault(
        int key,
        sdp.progetto.grpc.Statistics defaultValue) {
      
      java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> map =
          internalGetStats().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */
    @java.lang.Override

    public sdp.progetto.grpc.Statistics getStatsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> map =
          internalGetStats().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearStats() {
      internalGetMutableStats().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */

    public Builder removeStats(
        int key) {
      
      internalGetMutableStats().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics>
    getMutableStats() {
      return internalGetMutableStats().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */
    public Builder putStats(
        int key,
        sdp.progetto.grpc.Statistics value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableStats().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, .Statistics&gt; stats = 1;</code>
     */

    public Builder putAllStats(
        java.util.Map<java.lang.Integer, sdp.progetto.grpc.Statistics> values) {
      internalGetMutableStats().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TokenData)
  }

  // @@protoc_insertion_point(class_scope:TokenData)
  private static final sdp.progetto.grpc.TokenData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdp.progetto.grpc.TokenData();
  }

  public static sdp.progetto.grpc.TokenData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenData>
      PARSER = new com.google.protobuf.AbstractParser<TokenData>() {
    @java.lang.Override
    public TokenData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TokenData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TokenData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TokenData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdp.progetto.grpc.TokenData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

