// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anello.proto

package sdp.progetto.grpc;

/**
 * Protobuf type {@code UpdateData}
 */
public final class UpdateData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpdateData)
    UpdateDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateData.newBuilder() to construct.
  private UpdateData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateData() {
    houses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sender_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              houses_ = new java.util.ArrayList<sdp.progetto.grpc.HouseData>();
              mutable_bitField0_ |= 0x00000001;
            }
            houses_.add(
                input.readMessage(sdp.progetto.grpc.HouseData.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        houses_ = java.util.Collections.unmodifiableList(houses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdp.progetto.grpc.Anello.internal_static_UpdateData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdp.progetto.grpc.Anello.internal_static_UpdateData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdp.progetto.grpc.UpdateData.class, sdp.progetto.grpc.UpdateData.Builder.class);
  }

  public static final int SENDER_FIELD_NUMBER = 1;
  private int sender_;
  /**
   * <code>int32 sender = 1;</code>
   * @return The sender.
   */
  @java.lang.Override
  public int getSender() {
    return sender_;
  }

  public static final int HOUSES_FIELD_NUMBER = 2;
  private java.util.List<sdp.progetto.grpc.HouseData> houses_;
  /**
   * <code>repeated .HouseData houses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<sdp.progetto.grpc.HouseData> getHousesList() {
    return houses_;
  }
  /**
   * <code>repeated .HouseData houses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends sdp.progetto.grpc.HouseDataOrBuilder> 
      getHousesOrBuilderList() {
    return houses_;
  }
  /**
   * <code>repeated .HouseData houses = 2;</code>
   */
  @java.lang.Override
  public int getHousesCount() {
    return houses_.size();
  }
  /**
   * <code>repeated .HouseData houses = 2;</code>
   */
  @java.lang.Override
  public sdp.progetto.grpc.HouseData getHouses(int index) {
    return houses_.get(index);
  }
  /**
   * <code>repeated .HouseData houses = 2;</code>
   */
  @java.lang.Override
  public sdp.progetto.grpc.HouseDataOrBuilder getHousesOrBuilder(
      int index) {
    return houses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sender_ != 0) {
      output.writeInt32(1, sender_);
    }
    for (int i = 0; i < houses_.size(); i++) {
      output.writeMessage(2, houses_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sender_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sender_);
    }
    for (int i = 0; i < houses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, houses_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdp.progetto.grpc.UpdateData)) {
      return super.equals(obj);
    }
    sdp.progetto.grpc.UpdateData other = (sdp.progetto.grpc.UpdateData) obj;

    if (getSender()
        != other.getSender()) return false;
    if (!getHousesList()
        .equals(other.getHousesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender();
    if (getHousesCount() > 0) {
      hash = (37 * hash) + HOUSES_FIELD_NUMBER;
      hash = (53 * hash) + getHousesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdp.progetto.grpc.UpdateData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.UpdateData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.UpdateData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdp.progetto.grpc.UpdateData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdp.progetto.grpc.UpdateData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpdateData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdateData)
      sdp.progetto.grpc.UpdateDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdp.progetto.grpc.Anello.internal_static_UpdateData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdp.progetto.grpc.Anello.internal_static_UpdateData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdp.progetto.grpc.UpdateData.class, sdp.progetto.grpc.UpdateData.Builder.class);
    }

    // Construct using sdp.progetto.grpc.UpdateData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHousesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sender_ = 0;

      if (housesBuilder_ == null) {
        houses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        housesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdp.progetto.grpc.Anello.internal_static_UpdateData_descriptor;
    }

    @java.lang.Override
    public sdp.progetto.grpc.UpdateData getDefaultInstanceForType() {
      return sdp.progetto.grpc.UpdateData.getDefaultInstance();
    }

    @java.lang.Override
    public sdp.progetto.grpc.UpdateData build() {
      sdp.progetto.grpc.UpdateData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdp.progetto.grpc.UpdateData buildPartial() {
      sdp.progetto.grpc.UpdateData result = new sdp.progetto.grpc.UpdateData(this);
      int from_bitField0_ = bitField0_;
      result.sender_ = sender_;
      if (housesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          houses_ = java.util.Collections.unmodifiableList(houses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.houses_ = houses_;
      } else {
        result.houses_ = housesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdp.progetto.grpc.UpdateData) {
        return mergeFrom((sdp.progetto.grpc.UpdateData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdp.progetto.grpc.UpdateData other) {
      if (other == sdp.progetto.grpc.UpdateData.getDefaultInstance()) return this;
      if (other.getSender() != 0) {
        setSender(other.getSender());
      }
      if (housesBuilder_ == null) {
        if (!other.houses_.isEmpty()) {
          if (houses_.isEmpty()) {
            houses_ = other.houses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHousesIsMutable();
            houses_.addAll(other.houses_);
          }
          onChanged();
        }
      } else {
        if (!other.houses_.isEmpty()) {
          if (housesBuilder_.isEmpty()) {
            housesBuilder_.dispose();
            housesBuilder_ = null;
            houses_ = other.houses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            housesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHousesFieldBuilder() : null;
          } else {
            housesBuilder_.addAllMessages(other.houses_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sdp.progetto.grpc.UpdateData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sdp.progetto.grpc.UpdateData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int sender_ ;
    /**
     * <code>int32 sender = 1;</code>
     * @return The sender.
     */
    @java.lang.Override
    public int getSender() {
      return sender_;
    }
    /**
     * <code>int32 sender = 1;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(int value) {
      
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sender = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<sdp.progetto.grpc.HouseData> houses_ =
      java.util.Collections.emptyList();
    private void ensureHousesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        houses_ = new java.util.ArrayList<sdp.progetto.grpc.HouseData>(houses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sdp.progetto.grpc.HouseData, sdp.progetto.grpc.HouseData.Builder, sdp.progetto.grpc.HouseDataOrBuilder> housesBuilder_;

    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public java.util.List<sdp.progetto.grpc.HouseData> getHousesList() {
      if (housesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(houses_);
      } else {
        return housesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public int getHousesCount() {
      if (housesBuilder_ == null) {
        return houses_.size();
      } else {
        return housesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public sdp.progetto.grpc.HouseData getHouses(int index) {
      if (housesBuilder_ == null) {
        return houses_.get(index);
      } else {
        return housesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder setHouses(
        int index, sdp.progetto.grpc.HouseData value) {
      if (housesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousesIsMutable();
        houses_.set(index, value);
        onChanged();
      } else {
        housesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder setHouses(
        int index, sdp.progetto.grpc.HouseData.Builder builderForValue) {
      if (housesBuilder_ == null) {
        ensureHousesIsMutable();
        houses_.set(index, builderForValue.build());
        onChanged();
      } else {
        housesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder addHouses(sdp.progetto.grpc.HouseData value) {
      if (housesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousesIsMutable();
        houses_.add(value);
        onChanged();
      } else {
        housesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder addHouses(
        int index, sdp.progetto.grpc.HouseData value) {
      if (housesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHousesIsMutable();
        houses_.add(index, value);
        onChanged();
      } else {
        housesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder addHouses(
        sdp.progetto.grpc.HouseData.Builder builderForValue) {
      if (housesBuilder_ == null) {
        ensureHousesIsMutable();
        houses_.add(builderForValue.build());
        onChanged();
      } else {
        housesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder addHouses(
        int index, sdp.progetto.grpc.HouseData.Builder builderForValue) {
      if (housesBuilder_ == null) {
        ensureHousesIsMutable();
        houses_.add(index, builderForValue.build());
        onChanged();
      } else {
        housesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder addAllHouses(
        java.lang.Iterable<? extends sdp.progetto.grpc.HouseData> values) {
      if (housesBuilder_ == null) {
        ensureHousesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, houses_);
        onChanged();
      } else {
        housesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder clearHouses() {
      if (housesBuilder_ == null) {
        houses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        housesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public Builder removeHouses(int index) {
      if (housesBuilder_ == null) {
        ensureHousesIsMutable();
        houses_.remove(index);
        onChanged();
      } else {
        housesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public sdp.progetto.grpc.HouseData.Builder getHousesBuilder(
        int index) {
      return getHousesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public sdp.progetto.grpc.HouseDataOrBuilder getHousesOrBuilder(
        int index) {
      if (housesBuilder_ == null) {
        return houses_.get(index);  } else {
        return housesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public java.util.List<? extends sdp.progetto.grpc.HouseDataOrBuilder> 
         getHousesOrBuilderList() {
      if (housesBuilder_ != null) {
        return housesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(houses_);
      }
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public sdp.progetto.grpc.HouseData.Builder addHousesBuilder() {
      return getHousesFieldBuilder().addBuilder(
          sdp.progetto.grpc.HouseData.getDefaultInstance());
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public sdp.progetto.grpc.HouseData.Builder addHousesBuilder(
        int index) {
      return getHousesFieldBuilder().addBuilder(
          index, sdp.progetto.grpc.HouseData.getDefaultInstance());
    }
    /**
     * <code>repeated .HouseData houses = 2;</code>
     */
    public java.util.List<sdp.progetto.grpc.HouseData.Builder> 
         getHousesBuilderList() {
      return getHousesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sdp.progetto.grpc.HouseData, sdp.progetto.grpc.HouseData.Builder, sdp.progetto.grpc.HouseDataOrBuilder> 
        getHousesFieldBuilder() {
      if (housesBuilder_ == null) {
        housesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sdp.progetto.grpc.HouseData, sdp.progetto.grpc.HouseData.Builder, sdp.progetto.grpc.HouseDataOrBuilder>(
                houses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        houses_ = null;
      }
      return housesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpdateData)
  }

  // @@protoc_insertion_point(class_scope:UpdateData)
  private static final sdp.progetto.grpc.UpdateData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdp.progetto.grpc.UpdateData();
  }

  public static sdp.progetto.grpc.UpdateData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateData>
      PARSER = new com.google.protobuf.AbstractParser<UpdateData>() {
    @java.lang.Override
    public UpdateData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdp.progetto.grpc.UpdateData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

